version: '3.8'
services:
  postgres:
    container_name: postgresql
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=listify
    volumes:
      - listify_data:/var/lib/postgresql
volumes:
  listify_data: